---
title: "Codebook"
author: "Debra Cooperman"
date: "January 24, 2015"
output: html_document
---

### DATA DICTIONARY - Tidy Data  

SUBJECT  

 Integer number indicating 1 of 30 total subjects who participated  
 in the experiments:  
 1 Subject 1    
 2 Subject 2  
 3 Subject 3  
 4 Subject 4  
 5 Subject 5   
 6 Subject 6  
 7 Subject 7  
 8 Subject 8  
 9 Subject 9  
 10 Subject 10  
 11 Subject 11  
 12 Subject 12  
 13 Subject 13  
 14 Subject 14  
 15 Subject 15  
 16 Subject 16  
 17 Subject 17  
 18 Subject 18  
 19 Subject 19  
 20 Subject 20  
 21 Subject 21  
 22 Subject 22  
 23 Subject 23  
 24 Subject 24  
 25 Subject 25    
 26 Subject 26  
 27 Subject 27  
 28 Subject 28  
 29 Subject 29  
 30 Subject 30
 
ACTIVITY  
 
One of 6 activities participated in by each of the subjects:  
Walking  
Walking_Upstairs  
Walking_Downstairs  
Sitting  
Standing  
Laying  

AVERAGES of MEAN and STANDARD DEVIATION for ACCELEROMETER and GYROSCOPE 3-AXIAL(XYZ)    
SIGNALS (measured in HZ)

Each of these variables is the mean, weighted average or standard deviation of  
a time domain signal (indicated by a "t" prefix, or a frequency domain signal  
(indicated by an "f" prefix). The term "gyro" means "gyroscope", and the term  
"Acc" means acclerometer. The acceleration signals were divided into "body"  
and "gravity" signals, which are found in some of the variables.  

Subsequently, the body linear acceleration and angular velocity were derived  
in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also  
the magnitude of these three-dimensional signals were calculated using the   
Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag,   
tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals  
producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag,  
fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals).  

Lastly, the value of each of these variables is the mean of the original values  
grouped by Subject and Activity. 

tBodyAcc.mean...X                     
tBodyAcc.mean...Y  
tBodyAcc.mean...Z  
tGravityAcc.mean...X                  
tGravityAcc.mean...Y  
tGravityAcc.mean...Z  
tBodyAccJerk.mean...X               
tBodyAccJerk.mean...Y  
tBodyAccJerk.mean...Z  
tBodyGyro.mean...X                    
tBodyGyro.mean...Y  
tBodyGyro.mean...Z                    
tBodyGyroJerk.mean...X                
tBodyGyroJerk.mean...Y  
tBodyGyroJerk.mean...Z  
tBodyAccMag.mean..  
tGravityAccMag.mean..  
tBodyAccJerkMag.mean..  
tBodyGyroMag.mean..                   
tBodyGyroJerkMag.mean..  
fBodyAcc.mean...X                     
fBodyAcc.mean...Y                     
fBodyAcc.mean...Z  
fBodyAcc.meanFreq...X  
fBodyAcc.meanFreq...Y                 
fBodyAcc.meanFreq...Z                  
fBodyAccJerk.mean...X                  
fBodyAccJerk.mean...Y               
fBodyAccJerk.mean...Z  
fBodyAccJerk.meanFreq...X  
fBodyAccJerk.meanFreq...Y  
fBodyAccJerk.meanFreq...Z  
fBodyGyro.mean...X  
fBodyGyro.mean...Y                   
fBodyGyro.mean...Z                     
fBodyGyro.meanFreq...X                   
fBodyGyro.meanFreq...Y                
fBodyGyro.meanFreq...Z                 
fBodyAccMag.mean..  
fBodyAccMag.meanFreq..                
fBodyBodyAccJerkMag.mean..  
fBodyBodyAccJerkMag.meanFreq..  
fBodyBodyGyroMag.mean..               
fBodyBodyGyroMag.meanFreq..  
fBodyBodyGyroJerkMag.mean..            
fBodyBodyGyroJerkMag.meanFreq..       
angle.tBodyAccMean.gravity.  
angle.tBodyAccJerkMean..gravityMean.  
angle.tBodyGyroMean.gravityMean.  
angle.tBodyGyroJerkMean.gravityMean.  
angle.X.gravityMean.  
angle.Y.gravityMean.                 
angle.Z.gravityMean.                   
tBodyAcc.std...X  
tBodyAcc.std...Y                      
tBodyAcc.std...Z                       
tGravityAcc.std...X                   
tGravityAcc.std...Y                   
tGravityAcc.std...Z                    
tBodyAccJerk.std...X  
tBodyAccJerk.std...Y  
tBodyAccJerk.std...Z  
tBodyGyro.std...X  
tBodyGyro.std...Y  
tBodyGyro.std...Z                     
tBodyGyroJerk.std...X  
tBodyGyroJerk.std...Y                 
tBodyGyroJerk.std...Z                  
tBodyAccMag.std..                     
tGravityAccMag.std..                  
tBodyAccJerkMag.std..                  
tBodyGyroMag.std..  
tBodyGyroJerkMag.std..                
fBodyAcc.std...X                       
fBodyAcc.std...Y                       
fBodyAcc.std...Z                     
fBodyAccJerk.std...X                   
fBodyAccJerk.std...Y                   
fBodyAccJerk.std...Z                  
fBodyGyro.std...X                      
fBodyGyro.std...Y                      
fBodyGyro.std...Z                     
fBodyAccMag.std..                      
fBodyBodyAccJerkMag.std..  
fBodyBodyGyroMag.std..  
fBodyBodyGyroJerkMag.std..           